Adds new electronic holdings record
sul-dlss/libsys-airflow pull request #103
Opened 2022-06-16 21:03 UTC by jermnelson

Fixes #102. 

TODO:
- [x] Add correct `LOCATION` to Electronic holdings tsv
- [x] Troubleshoot mapping errors: 
 ```
[2022-06-16, 20:51:35 UTC] {custom_exceptions.py:52} DATA_ISSUES - RECORD FAILED	ddbc76ae-0977-4f87-93b2-f6cded6db65b	Bib id not in instance id map.	a14240796
[2022-06-16, 20:51:35 UTC] {custom_exceptions.py:51} ERROR - Record failed: Bib id not in instance id map.. See the data issues log for details
```
- [x] Linting errors
- [x] Unit tests

2022-08-02 21:45 UTC, shelleydoljack commented on plugins/folio/helpers.py
> +            row["PUBLIC_NOTE"] = " ".join(public_note)
Are multiple public notes supposed to be mapped to one folio electronicAccess.publicNote field or multiple? If multiple, then probably going to need to join with something other than a space.

2022-08-02 22:35 UTC, shelleydoljack commented on plugins/folio/helpers.py
> +            row["PUBLIC_NOTE"] = " ".join(public_note)
Per Alissa, only one publicNote field is allowed per URL so this seems fine to join with a space.

2022-08-04 20:07 UTC, shelleydoljack requested changes

2022-08-04 20:07 UTC, shelleydoljack commented on plugins/tests/test_helpers.py
> +    assert _add_electronic_holdings(field_856) is True
Oh, ok, so holdings are getting added when indicator2 is 0.

2022-08-04 20:19 UTC, jermnelson commented on plugins/folio/helpers.py
> +    return True
> This method should also return true if 856 indicator2 is 0, unless that is handled elsewhere, although I haven't seen that. The full_text_check against subfields z and 3 is really only for when 856 indicator2 is 1.

Yes, this method will return true if indicator2 is 0.

2022-08-04 20:20 UTC, jermnelson commented on plugins/folio/holdings.py
> +        default_call_number_type_name="Library of Congress classification",
Not sure, who would know? @ahafele?

2022-08-04 20:22 UTC, jermnelson commented on plugins/folio/helpers.py
> +    return catkey
This has been the going assumption for all of the bib record loads.

2022-08-09 20:16 UTC, shelleydoljack commented on plugins/folio/holdings.py
> +        default_call_number_type_name="Library of Congress classification",
I don't actually see that a call number type got assigned so 🤷

2022-08-09 20:17 UTC, shelleydoljack approved these changes

2022-08-09 20:17 UTC, merged