Use Change Manager Okapi Endpoint to update MARC
sul-dlss/libsys-airflow pull request #1034
Opened 2024-05-28 22:11 UTC by jermnelson

Fixes #1010

2024-05-29 22:32 UTC, shelleydoljack requested changes

2024-05-29 22:32 UTC, shelleydoljack commented on libsys_airflow/plugins/data_exports/oclc_api.py
> +                "externalidsHolder": {"instanceId": instance_uuid},
Typo: should be `externalIdsHolder`

2024-05-29 22:39 UTC, jermnelson commented on libsys_airflow/plugins/data_exports/oclc_api.py
> +                "externalidsHolder": {"instanceId": instance_uuid},
Thanks! Just fixed in new commit.

2024-05-29 22:51 UTC, shelleydoljack requested changes

2024-05-29 22:51 UTC, shelleydoljack commented on libsys_airflow/plugins/data_exports/oclc_api.py
> +                "externalIdsHolder": {"instanceId": instance_uuid},
Sorry, I think we need to fix this more.... I started to realize that externalIdsHolder contains instanceHrid too. What happens to instanceHrid in this field if we do a PUT here? For example, let's take the data from prod: do a `GET /source-storage/source-records/0f6a7a68-4862-5452-89ee-9c21dab4ff8c` and you see 
```
"externalIdsHolder": {
  "instanceId": "e5e63507-5812-55db-9f08-36f4f43ea088",
  "instanceHrid": "a1461022"
}
```
This data allows one to use these API queries:
```
/source-storage/source-records?externalId=e5e63507-5812-55db-9f08-36f4f43ea088
/source-storage/source-records?instanceId=e5e63507-5812-55db-9f08-36f4f43ea088
/source-storage/source-records?instanceHrid=a1461022
/source-storage/source-records?externalHrid=a1461022
```
We need to add instanceHrid I think. If I try the GETs ☝️  on folio-dev using instanceId `c009b09c-8e8a-5f23-a8f5-6fa22addcc18` I get data but not for hrid `a1461022`.

2024-05-30 14:17 UTC, jermnelson commented on libsys_airflow/plugins/data_exports/oclc_api.py
> +                "externalIdsHolder": {"instanceId": instance_uuid},
Hi Shelley, 
I'm not sure that is the case as the hrid still persists after doing a PUT to the change-manager. For https://folio-dev.stanford.edu/inventory/view/7a3a992e-0e05-5e5b-91da-8c1fd67233d7, I just used the instanceId and not the HRID.
```
"externalIdsHolder": {
         "instanceId": "7a3a992e-0e05-5e5b-91da-8c1fd67233d7"
  }
```
Doing a GET to `/inventory/instances/7a3a992e-0e05-5e5b-91da-8c1fd67233d7` returns the JSON with the HRID still present:

```
{'id': '7a3a992e-0e05-5e5b-91da-8c1fd67233d7',
 '_version': '4',
 'hrid': 'a602640',
 'source': 'MARC',
 'title': 'Artificial intelligence through simulated evolution [by] Lawrence J. Fogel, Alvin J. Owens [and] Michael J. Walsh.',
 'administrativeNotes': ['Identifier(s) from previous system: a602640'],
 'indexTitle': 'Artificial intelligence through simulated evolution',
 'parentInstances': [],
 'childInstances': [],
 'isBoundWith': False,
 'alternativeTitles': [],
 'editions': [],
 'series': [],
 'identifiers': [{'identifierTypeId': 'c858e4f2-2b6b-4385-842b-60732ee14abb',
   'value': '66021067'},
  {'identifierTypeId': '439bfbae-75bc-4f74-9fc7-b2a2d47ce3ef',
   'value': '(OCoLC-M)1208284'},
  {'identifierTypeId': '439bfbae-75bc-4f74-9fc7-b2a2d47ce3ef',
   'value': '(OCoLC-I)272601295'},
  {'identifierTypeId': '439bfbae-75bc-4f74-9fc7-b2a2d47ce3ef',
   'value': '(OCoLC)123Test'}],
   ````

2024-05-30 15:06 UTC, jermnelson commented on libsys_airflow/plugins/data_exports/oclc_api.py
> +                "externalIdsHolder": {"instanceId": instance_uuid},
Thanks @shelleydoljack,  good catch! Confirmed that if the`instanceHrid` is missing, the subsequent HRID related  queries to `/source-storage/source-records`  return nothing. Just pushed up a commit that adds the HRID to the change-manager PUT payload.

2024-05-30 16:18 UTC, shelleydoljack approved these changes

2024-05-30 17:01 UTC, jgreben approved these changes

2024-05-30 17:01 UTC, merged