Fixes bug for archiving of GOBI files
sul-dlss/libsys-airflow pull request #1051
Opened 2024-06-03 22:07 UTC by shelleydoljack

Fixes #1047 

I found myself jumping through hoops trying to address this issue on the `archive_transmitted_data_task` side. The prefix "stf." was part of the filename being looked for in the instanceids directory and related marc files to archive after the gobi ".txt" file is transmitted. I figured it would be easier if the "stf." was prepended when the file is uploaded to the GOBI ftp site since that is their spec for filenaming. We will have to do something similar for SHAREVDE anyways...

After re-writing the tests I then realized that maybe the vendor's filenaming convention should be in the extra field of the airflow Connection, like the remote_path is. If we want to go that route instead, I can make more changes.

2024-06-03 22:22 UTC, jgreben reviewed
I like the vendor filename spec idea. Can you point me to the lines where it is actually moving the .txt files to the transmitted folder? I see the comment about 
```
move marc files with same stem as transmitted filename (when transmitted file is not *.mrc)
```
but to me it looks like it is still just moving .mrc files. If it is moving .txt files to me it is very obfuscated.

2024-06-03 22:51 UTC, shelleydoljack commented
> I like the vendor filename spec idea. Can you point me to the lines where it is actually moving the .txt files to the transmitted folder? I see the comment about
> 
> ```
> move marc files with same stem as transmitted filename (when transmitted file is not *.mrc)
> ```
> 
> but to me it looks like it is still just moving .mrc files. If it is moving .txt files to me it is very obfuscated.

The archive task for GOBI gets a list of files that only includes the .txt files because that is what is sent to the transmit task: https://github.com/sul-dlss/libsys-airflow/blob/c664ace3093ee165542a603bb989931989e070bd/libsys_airflow/plugins/data_exports/transmission_tasks.py#L33-L36 The .txt files are moved here: https://github.com/sul-dlss/libsys-airflow/blob/c664ace3093ee165542a603bb989931989e070bd/libsys_airflow/plugins/data_exports/transmission_tasks.py#L228-L232

It is obfuscated by the fact that we create both marc and txt for gobi but only want to transmit txt files.

2024-06-03 23:23 UTC, jgreben commented
> The .txt files are moved here:
> https://github.com/sul-dlss/libsys-airflow/blob/c664ace3093ee165542a603bb989931989e070bd/libsys_airflow/plugins/data_exports/transmission_tasks.py#L228-L232
> 
> It is obfuscated by the fact that we create both marc and txt for gobi but only want to transmit txt files.

Thanks, can you please add blank lines on L210 and then on L211 and L216 in order to separate out the different paths and their comments? That block of code just makes it difficult to read what is happening there.

2024-06-03 23:24 UTC, jgreben requested changes
Please just reformat the `archive_transmitted_data_task` function to make it more readable. Thanks.

2024-06-03 23:31 UTC, jermnelson approved these changes
Looks good. Regarding your question about adding the vendor's file-naming convention to the connection extrajson, since we already have separate DAGs for each vendor, we could add custom file-naming configuration to pass through to more generic transmission tasks.

2024-06-04 17:52 UTC, shelleydoljack commented
> Looks good. Regarding your question about adding the vendor's file-naming convention to the connection extrajson, since we already have separate DAGs for each vendor, we could add custom file-naming configuration to pass through to more generic transmission tasks.

Maybe ticket-worthy for iteration 2 (when we add sharevde).

2024-06-04 19:21 UTC, jgreben approved these changes

2024-06-04 19:22 UTC, merged