Adds "Deletes" to OCLC API Wrapper
sul-dlss/libsys-airflow pull request #1061
Opened 2024-06-06 19:12 UTC by jermnelson

Fixes #968 

Calls BookOps `holdings_unset` for MARC record deletes from FOLIO.

2024-06-06 19:35 UTC, jermnelson commented on libsys_airflow/plugins/data_exports/oclc_api.py
> +    def __oclc_operations__(self, **kwargs) -> dict:
This method is part of DRYing the OCLCWrapper class, the public methods `new`, `update`, and `deletes` now define an inner function that is passed into the method.

2024-06-06 20:16 UTC, jgreben reviewed
I know it's not part of this PR, but where do`worldcat_metadata_url` and `auth_url` get used? https://github.com/sul-dlss/libsys-airflow/blob/5892892bcd70e2188d9a882b61ec1fbc63ab0cf5/libsys_airflow/plugins/data_exports/oclc_api.py#L23-24

Same for the `__del__` method? https://github.com/sul-dlss/libsys-airflow/blob/5892892bcd70e2188d9a882b61ec1fbc63ab0cf5/libsys_airflow/plugins/data_exports/oclc_api.py#L34

2024-06-06 21:20 UTC, shelleydoljack approved these changes

2024-06-06 21:20 UTC, shelleydoljack commented on libsys_airflow/plugins/data_exports/oclc_api.py
> +    def __oclc_operations__(self, **kwargs) -> dict:
I'm not sure I understand why we are defining an inner function but if it's to get it to work within our DAGs then I guess that's okay.

2024-06-06 21:20 UTC, shelleydoljack commented on libsys_airflow/plugins/data_exports/transmission_tasks.py
> +    return {"success": success, "failures": failures, "archive": archive}
What happens to the success and failures lists? Are these the transitory MARC files that we delete?

2024-06-06 21:51 UTC, jermnelson commented on libsys_airflow/plugins/data_exports/transmission_tasks.py
> +    return {"success": success, "failures": failures, "archive": archive}
We are currently not doing anything with either; they both contain Instance UUIDs that could be used to construct FOLIO URLs for email reports in follow-up PRs.

2024-06-06 21:55 UTC, jermnelson commented on libsys_airflow/plugins/data_exports/oclc_api.py
> +    def __oclc_operations__(self, **kwargs) -> dict:
In the previous `new` and `update` functions we were repeating the same code to set-up the output,  sets used to track files, and the `MetadataSession` session context. The new `delete` function would have needed to repeat the same boilerplate so creating the `__oclc_operations__` method allowed us to move that boilerplate to a single function and just pass in the functions that differed by operation.

2024-06-06 22:02 UTC, jermnelson commented
> I know it's not part of this PR, but where do`worldcat_metadata_url` and `auth_url` get used?
> 
> https://github.com/sul-dlss/libsys-airflow/blob/5892892bcd70e2188d9a882b61ec1fbc63ab0cf5/libsys_airflow/plugins/data_exports/oclc_api.py#L23-L24
> 
> Same for the `__del__` method?
> 
> https://github.com/sul-dlss/libsys-airflow/blob/5892892bcd70e2188d9a882b61ec1fbc63ab0cf5/libsys_airflow/plugins/data_exports/oclc_api.py#L34

Good catch, I just pushed up a commit that removes the 1worldcat_metadata_url` and `auth_url` that were left over when I wasn't using the BookOps package. The `__del__` method is necessary to close the `httpx.Client` that we're using for the the HTTP pooling of PUTs to FOLIO. Not explictly closing the Client was causing problems during testing.

2024-06-06 22:18 UTC, jgreben commented
> > https://github.com/sul-dlss/libsys-airflow/blob/5892892bcd70e2188d9a882b61ec1fbc63ab0cf5/libsys_airflow/plugins/data_exports/oclc_api.py#L34
> 
> Good catch, I just pushed up a commit that removes the `worldcat_metadata_url` and `auth_url` that were left over when I wasn't using the BookOps package. The `__del__` method is necessary to close the `httpx.Client` that we're using for the the HTTP pooling of PUTs to FOLIO. Not explictly closing the Client was causing problems during testing.

But I do not find a reference to the `__del__` method anywhere when I do a search ¯\_(ツ)_/¯ .

2024-06-06 22:29 UTC, jgreben requested changes
Check that `self.__del__` is called where and if needed.

2024-06-07 16:43 UTC, jgreben approved these changes

2024-06-07 16:43 UTC, merged