Adds email report for new and updated digital bookplates.
sul-dlss/libsys-airflow pull request #1193
Opened 2024-09-09 23:05 UTC by shelleydoljack

Closes #1184

2024-09-10 16:20 UTC, jermnelson commented on libsys_airflow/plugins/digital_bookplates/email.py
> +        <ul>
Would creating a table instead of unordered list be easier to understand in the email? Each line would be a table row so that we're not depending on `\t` to separate each value in the line? i.e
```
<tr>
  <th>Fund Name</th>
  <th>Druid</td>
  <th>Bookplate Image</th>
  <th>Reason</th>
 </tr>
 ...
<tr>
   <td>Fund name</td>
   <td>ab123cd4567</td>
    <td>image_ab123cd4567.jp2</td>
    <td>Title</td>
</tr>
```

2024-09-10 17:39 UTC, shelleydoljack commented on libsys_airflow/plugins/digital_bookplates/email.py
> +        <ul>
🤔 I see you added Reason as a header. We should add reason to tracking changes I think. I will update #1180 to add "reason" for an update. A table in the email would definitely make it easier to read. So I'll make that change. 
I think this task will be getting data from the XCOM from the task that adds or updates our table data. I'm not sure what our structure in the XCOM will look like exactly. I'll change the fixture to something more JSON-ny than a tsv string. Thanks for the suggestion!

2024-09-10 19:24 UTC, jgreben requested changes
I don't think the OKAPI_URL variable needs to be in the test fixture.

2024-09-10 20:33 UTC, shelleydoljack commented on tests/digital_bookplates/test_bookplates_emails.py
> +            case "OKAPI_URL":
Yes, because the digital bookplates email calls the is_production function.

2024-09-10 20:41 UTC, jgreben approved these changes

2024-09-11 00:29 UTC, jermnelson approved these changes

2024-09-11 00:29 UTC, merged