Run cap tasks per database; Cleanup readme and docker files.
sul-dlss/libsys-airflow pull request #1201
Opened 2024-09-11 18:59 UTC by jgreben

2024-09-11 20:17 UTC, shelleydoljack approved these changes
Just some non-blocking questions about readme and docker-compose cleanup.

2024-09-11 20:17 UTC, shelleydoljack commented on README.md
> -### For Aeon and Lobbytrack API calls
Do we also want to cleanup the above section about running airflow in k8s?

2024-09-11 20:17 UTC, shelleydoljack commented on README.md
> -### For Aeon and Lobbytrack API calls
And remove the section "Running the DAGs to load Folio Inventory"?

2024-09-11 20:17 UTC, shelleydoljack commented on docker-compose.prod.yaml
> -    AIRFLOW_VAR_LOBBY_KEY: ${AIRFLOW_VAR_LOBBY_KEY}
Remove also `AIRFLOW_VAR_MIGRATION_*` variables? Unless those are used in the other DAGs?

2024-09-11 21:43 UTC, shelleydoljack approved these changes

2024-09-11 21:43 UTC, shelleydoljack commented on config/deploy.rb
> +end
Is this to only run alembic tasks for a specific db? If this is for new dbs, then why not just add to `set :alembic_dbs, ['vma', 'digital_bookplates']` to run?

2024-09-11 23:53 UTC, jgreben commented on config/deploy.rb
> +end
This is to address the issue description for #1200: "It might be nice to run only the migration for specific database but also continue having a task that runs all of the migration."

2024-09-12 15:14 UTC, jermnelson requested changes
Minor comment about a line that looks like it needs to be uncommented

2024-09-12 15:14 UTC, jermnelson commented on config/deploy.rb
> +        # execute "cd #{release_path} && source #{fetch(:venv)} && poetry run alembic --name #{database} upgrade head"
Should this be uncommented?

2024-09-12 16:44 UTC, jermnelson approved these changes

2024-09-12 16:44 UTC, merged