Paid invoices and invoice lines data
sul-dlss/libsys-airflow pull request #1239
Opened 2024-10-03 04:03 UTC by shelleydoljack

Closes #1218 and #1209 

Need to add tests....

2024-10-03 23:28 UTC, shelleydoljack commented on libsys_airflow/plugins/folio/invoices.py
> +    ]
As I was writing the test, I started to wonder why we even want the invoice line UUID here as key. Maybe for troubleshooting? We could have invoice lines that do not have fundDistributions (it is not required per json schema docs) and also no po line ID. So if the fund ID is missing or po line is missing, we don't want that data. Currently, in those cases, the filter_invoice_lines list can include an object like:
```
{"a16030c1-66ca-44c1-b0a3-572cde626685": {}}
```

2024-10-04 15:17 UTC, jermnelson commented on libsys_airflow/plugins/folio/invoices.py
> +    ]
Or maybe in reporting in an email?

2024-10-04 16:17 UTC, jermnelson requested changes

2024-10-04 16:17 UTC, jermnelson commented on libsys_airflow/dags/digital_bookplates/digital_bookplate_instances.py
> +    retrieve_instances = instances_from_po_lines(retrieve_bookplate_fund_po_lines)
The `instances_from_po_lines` is missing a required `funds` parameter

2024-10-04 17:15 UTC, shelleydoljack commented on libsys_airflow/plugins/folio/invoices.py
> +    ]
Maybe we change this in a subsequent PR if unpacking this list is problematic with the empty objects for invoicelines that don't have funds or po lines.

2024-10-04 17:15 UTC, shelleydoljack commented on libsys_airflow/dags/digital_bookplates/digital_bookplate_instances.py
> +    retrieve_instances = instances_from_po_lines(retrieve_bookplate_fund_po_lines)
Fixed in latest commit.

2024-10-04 17:17 UTC, jermnelson approved these changes

2024-10-04 17:17 UTC, merged