Skip OCLC records op if not prod
sul-dlss/libsys-airflow pull request #1380
Opened 2024-10-29 21:00 UTC by jgreben

Fixes #1054

2024-10-29 22:37 UTC, jermnelson commented
We may want to hold off merging this PR until we hear from @ahafele, I think she is still doing testing on Airflow test.

2024-11-15 16:32 UTC, shelleydoljack requested changes

2024-11-15 16:32 UTC, shelleydoljack commented on libsys_airflow/plugins/data_exports/oclc_api.py
> +        )
I think we still need to put something in archive_files in order to move the selection files to the transmitted directory (even though we aren't transmitting them in dev and stage envs).

2024-11-18 18:57 UTC, shelleydoljack requested changes
I think the test `test_oclc_marc_modifications` got dropped inadvertently.

2024-11-18 18:57 UTC, shelleydoljack commented on tests/data_exports/test_oclc_api.py
> -    assert second_mod["040"]["a"] == "STF"
These test are now missing. Is that right?

2024-11-18 22:01 UTC, jgreben commented on tests/data_exports/test_oclc_api.py
> -    assert second_mod["040"]["a"] == "STF"
I rebased and then merged. The missing test is back.

2024-11-18 22:10 UTC, shelleydoljack approved these changes
👍

2024-11-18 22:35 UTC, merged