Log errors but do not raise SystemExit for encumbrances script
sul-dlss/libsys-airflow pull request #1426
Opened 2024-11-11 15:46 UTC by jgreben

The fix_encumbrances dag will not email the log if there is an error that raises SystemExit(1). Log the errors and always complete the script.

2024-11-11 16:10 UTC, jermnelson requested changes

2024-11-11 16:10 UTC, jermnelson commented on libsys_airflow/plugins/folio/encumbrances/fix_encumbrances.py
> +        # raise SystemExit(1)
Any reason why to keep this line commented out, `# SystemExit(1)` instead of just removing here and the other similar lines in this PR?

2024-11-11 16:10 UTC, jermnelson commented on libsys_airflow/plugins/folio/encumbrances/fix_encumbrances.py
> +            # raise SystemExit(1)
See comment above

2024-11-11 16:17 UTC, jgreben commented on libsys_airflow/plugins/folio/encumbrances/fix_encumbrances.py
> +        # raise SystemExit(1)
Because we will likely need to revisit and re-implement this script when there is a new version of it, I would like to keep a documentation of the edits to make it easier to re-do what we did to make it work.

2024-11-11 16:18 UTC, jgreben commented on libsys_airflow/plugins/folio/encumbrances/fix_encumbrances.py
> +            # raise SystemExit(1)
Same answer as above

2024-11-11 17:23 UTC, jermnelson approved these changes

2024-11-12 17:07 UTC, jgreben commented
I modified the fix_encumbrances script to print the "info" and "warning" statements to stdout (the log file) and the "errors" to both stdout and the logger.

2024-11-12 17:57 UTC, shelleydoljack approved these changes
Do you want to address the non-zero amounts thing here or in a different PR? I'm okay either way.

2024-11-12 17:57 UTC, shelleydoljack commented on libsys_airflow/plugins/folio/encumbrances/fix_encumbrances.py
> +    print('Unreleasing open orders encumbrances with non-zero amounts...')
Is this the one where we updated it to fix it even if it has zero amounts? I think we should fixup the warning message too.

2024-11-12 18:17 UTC, jgreben commented on libsys_airflow/plugins/folio/encumbrances/fix_encumbrances.py
> +    print('Unreleasing open orders encumbrances with non-zero amounts...')
I think that was https://github.com/sul-dlss/libsys-airflow/blob/0bfa734681cf92ff820197f6f185bb48b289cb3c/libsys_airflow/plugins/folio/encumbrances/fix_encumbrances.py#L491 ?

2024-11-12 18:26 UTC, merged