Use poetry to manage python dependencies
sul-dlss/libsys-airflow pull request #284
Opened 2023-04-06 19:25 UTC by mjgiarlo

Fixes #276

This commit changes how python dependencies are managed in libsys-airflow, switching from `pip` to `poetry`. This particularly affects the DAGs and plugins we load into the docker-run Airflow instance. To load these poetry-managed dependencies into the running Airflow instance, we integrate `poetry build` and `pip` via the wheel packaging standard.

As part of this work, we move the directories that need the poetry-managed dependencies into a new directory, `libsys_airflow`, as that is a requirement of `poetry build`, so a large number of renames (moves) are included in this commit. This directory is now where all of the python work is handled.

2023-04-06 20:09 UTC, mjgiarlo commented on README.md
> +1. Install docker-compose in the poetry virtual environment: `poetry shell && pip3 install docker-compose`
One of the changes I'll want help testing is around the venv changes here. It's not clear to me how venv was being used before (single purpose? multiple?) and whether the changes I've made here in the README are broken or unnecessary.

2023-04-06 20:10 UTC, mjgiarlo commented on pyproject.toml
> +folio-uuid = "^0.2.8"
Manage all dependencies (prod and dev/test alike) in one place instead of `pip install`s sprinkled all over and commingling dependencies.

2023-04-06 20:11 UTC, mjgiarlo commented on docker-compose.yaml
> +    - ${AIRFLOW_PROJ_DIR:-.}/libsys_airflow/circ:/opt/airflow/circ
Move the working directories into the new python/poetry dir. Tidies up the root and makes clear where the python stuff's happening.

2023-04-06 20:12 UTC, mjgiarlo commented on docker-compose.yaml
> +    SQLALCHEMY_SILENCE_UBER_WARNING: 1
These muddy the docker-compose logs.

2023-04-06 20:12 UTC, mjgiarlo commented on config/deploy.rb
> +      execute "cd #{release_path} && pip3 install -r requirements.txt && poetry build --format=wheel --no-interaction --no-ansi && pip3 install dist/*.whl"
I don't think we need the venv here?

2023-04-06 20:14 UTC, mjgiarlo commented on README.md
> +1. On the server `poetry shell && pip3 install docker-compose==1.29.2`
I notice we use `pip` in some places and `pip3` in others. I'm not sure if we should care about consistency, or if we genuinely need this to vary in different contexts. 🤷🏻‍♂️

2023-04-06 20:14 UTC, mjgiarlo commented on .github/workflows/python-app.yml
> -        coveralls --service=github
Poetry handles all the deps now, so we no longer need to install new ones in CI.

2023-04-06 21:15 UTC, lwrubel commented on pyproject.toml
> +folio-uuid = "^0.2.8"
I think these are also development dependencies:

```
pytest
pytest-mock
pydantic
```

2023-04-06 21:42 UTC, mjgiarlo commented on pyproject.toml
> +folio-uuid = "^0.2.8"
@lwrubel I found that those needed to be prod dependencies, or airflow was unhappy. If a dependency is declared in the prod dependencies above, does it need to be explicitly listed as a dev dep?

2023-04-07 12:49 UTC, lwrubel commented on Dockerfile
> +RUN pip install dist/*.whl
I'm curious about using `poetry build` and then pip to install the wheels, rather than a regular `poetry install`. Is that a recommended practice for poetry in building a Docker image?

2023-04-07 13:07 UTC, lwrubel commented on README.md
> +1. Drop into the poetry virtual environment: `poetry shell`
The first time I ran through these instructions, I had to do `poetry install --with dev` to get the airflow dependency. Then I could run `poetry shell` and `pytest` successfully. 

I did a `docker build` once, to build the image and bring Airflow up. That worked. 

Now, starting again with a new poetry environment (I deactivated and removed the initial one, to start fresh), when doing `poetry build --format=wheel` I get:
```
'/opt/airflow/logs/scheduler/2023-04-07' is not in the subpath of '/Users/laurawrubel/sul-dlss/libsys-airflow' OR one path is relative and the other is absolute.`
```

I'm not sure if I messed things up with this order of steps, but happy to pair and show what I'm seeing.

2023-04-07 15:04 UTC, mjgiarlo commented on Dockerfile
> +RUN pip install dist/*.whl
@lwrubel I naïvely started doing `poetry install`, which is typically how I've used `poetry`. When I did that, Airflow seemingly did not "see" the dependencies when it started up. As far as I could tell, this two-step process is key to installing the `poetry`-managed dependencies into the Airflow environment (which relies on `pip`). Let me confirm that, though, and I'll drop another reply.

2023-04-07 15:05 UTC, mjgiarlo commented on README.md
> +1. Drop into the poetry virtual environment: `poetry shell`
Hmm. I had been seeing that before too until I added the `exclude` and `include` directories in `pyproject.toml`, and then that error went away for me. Maybe that wasn't the right fix, though. Thanks for testing!

2023-04-07 15:37 UTC, mjgiarlo commented on Dockerfile
> +RUN pip install dist/*.whl
Using `poetry install` in docker-land, causes Airflow's plugins to be unhappy:

```
airflow-webserver_1  | [2023-04-07 15:11:06,985] {plugins_manager.py:266} ERROR - Failed to import plugin /opt/airflow/plugins/folio/
helpers/marc.py                                                                                                                      
airflow-webserver_1  | Traceback (most recent call last):                                                                            
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.10/site-packages/airflow/plugins_manager.py", line 258, in load_plugi
ns_from_plugin_directory                                                                                                             
airflow-webserver_1  |     loader.exec_module(mod)                                                                                   
airflow-webserver_1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module                                     
airflow-webserver_1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                
airflow-webserver_1  |   File "/opt/airflow/plugins/folio/helpers/marc.py", line 10, in <module>                                     
airflow-webserver_1  |     import pymarc                                                                                             
airflow-webserver_1  | ModuleNotFoundError: No module named 'pymarc'           
```

2023-04-07 16:13 UTC, jermnelson commented on config/deploy.rb
> +      execute "cd #{release_path} && pip3 install -r requirements.txt && poetry build --format=wheel --no-interaction --no-ansi && pip3 install dist/*.whl"
We were using a Python 3.10 virtual environment because the VM's version of Python is 3.8 and is incompatible with the `folio_migration_tools`. This may not be necessary now that we're using poetry so further testing is needed.

2023-04-07 16:19 UTC, jermnelson commented on README.md
> +1. On the server `poetry shell && pip3 install docker-compose==1.29.2`
When in the virtual environment, `pip` and `pip3` are identical. When not using a virtual environment, pip3 is usually installed through Linux package manager and manages the system's Python 3 dependencies. When using `poetry shell` that activates a virtual environment, the `pip3` should be the local version and not the system version.

2023-04-07 16:20 UTC, mjgiarlo commented on README.md
> +1. Drop into the poetry virtual environment: `poetry shell`
@lwrubel I tossed a change at this branch if you want to re-pull and try again. I'm trying to verify here but my local python dev env is all mucked up because ... I don't currently known enough to unmuck it up. Happy to pair!

2023-04-07 16:21 UTC, mjgiarlo commented on README.md
> +1. On the server `poetry shell && pip3 install docker-compose==1.29.2`
@jermnelson OK, thank you! Happy to change anything here, since my local python dev env is janky.

2023-04-07 16:22 UTC, mjgiarlo commented on config/deploy.rb
> +      execute "cd #{release_path} && pip3 install -r requirements.txt && poetry build --format=wheel --no-interaction --no-ansi && pip3 install dist/*.whl"
Oh, then that is likely still broken (and probably related to some of the local python woes I'm having because ubuntu). I'll revert this change.

2023-04-07 16:22 UTC, jermnelson commented on pyproject.toml
> +folio-uuid = "^0.2.8"
FWIW  pydantic is `folio_migration_tools` dependency as well as development dependency that we are using for testing.

2023-04-07 16:23 UTC, jermnelson commented on docker-compose.yaml
> +    SQLALCHEMY_SILENCE_UBER_WARNING: 1
Cool! Nice addition.

2023-04-07 17:48 UTC, mjgiarlo commented on config/deploy.rb
> +      execute "cd #{release_path} && pip3 install -r requirements.txt && poetry build --format=wheel --no-interaction --no-ansi && pip3 install dist/*.whl"
Reverted this change.

2023-04-07 20:13 UTC, mjgiarlo commented on config/deploy.rb
> +    within releases_path do
This was a bug. (Unrelated to poetry but discovered when trying to re-deploy.)

2023-04-07 20:13 UTC, mjgiarlo commented on config/deploy.rb
> +      execute "[[ $(docker ps -aq) ]] && docker ps -aq | xargs docker stop | xargs docker rm || echo 'no containers to stop'"
A problem I discovered when re-deploying.

2023-04-07 20:20 UTC, lwrubel approved these changes

2023-04-07 20:54 UTC, jermnelson requested changes
One minor request for changing email with a few non-blocking questions.

2023-04-07 20:54 UTC, jermnelson commented on pyproject.toml
> +authors = ["Jeremy Nelson <jermnelson@gmail.com>", "Joshua Greben <jgreben@stanford.edu>", "Shelley Doljack", "Laura Wrubel", "Michael J. Giarlo <mjgiarlo@stanford.edu>"]
Could you change this to use my Stanford email `jpnelson@stanford.edu` instead of my personal gmail account?

2023-04-07 20:54 UTC, jermnelson commented on libsys_airflow/airflow.cfg
Does Airflow pick-up this configuration with it being moved to the `libsys_airflow` directory?

2023-04-07 20:54 UTC, jermnelson commented on README.md
> +* `poetry install`
I tried following these directions on the sul-libsys-airflow-prod and I ran into a conflict with the system's Python 3.8 version and poetry. The first line, `pip installed -r requirements` worked fine but then when I tried to the second command `poetry install`, I saw this error: 

```
 poetry install
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
The currently activated Python version 3.8.10 is not supported by the project (^3.10).
Trying to find and use a compatible version. 
```
Python 3.10.10 is currently installed on this VM in order to use the latest version of docker-compose so maybe we don't even need to install Poetry and the project's dependencies.

2023-04-07 20:54 UTC, jermnelson commented on README.md
> +* `poetry install`
This could very much be operator error on my part if the intention is not to install poetry on the server but for local development.

2023-04-07 21:44 UTC, mjgiarlo commented on README.md
> +* `poetry install`
@jermnelson Yeah, those instructions are only for local use. The steps that need to be run on the server are in the Dockerfile and in deploy.rb.

2023-04-07 21:46 UTC, mjgiarlo commented on libsys_airflow/airflow.cfg
@jermnelson Good question, because I'm not sure. How can we tell if `warn_deployment_exposure` has the right value in the running instance?

2023-04-07 21:46 UTC, mjgiarlo commented on pyproject.toml
> +authors = ["Jeremy Nelson <jermnelson@gmail.com>", "Joshua Greben <jgreben@stanford.edu>", "Shelley Doljack", "Laura Wrubel", "Michael J. Giarlo <mjgiarlo@stanford.edu>"]
Yep!

2023-04-07 21:47 UTC, mjgiarlo commented on pyproject.toml
> +authors = ["Jeremy Nelson <jermnelson@gmail.com>", "Joshua Greben <jgreben@stanford.edu>", "Shelley Doljack", "Laura Wrubel", "Michael J. Giarlo <mjgiarlo@stanford.edu>"]
Done.

2023-04-07 21:49 UTC, mjgiarlo commented
@jermnelson 💬 
> One minor request for changing email with a few non-blocking questions.

Other than not knowing whether airflow.cfg is picked up, this should be ready to go. Thanks for the review!

2023-04-07 22:19 UTC, jermnelson commented on libsys_airflow/airflow.cfg
I logged into the running container and ran the following [command](https://airflow.apache.org/docs/apache-airflow/stable/howto/set-config.html) 

```bash
airflow@580cf45ee73f:/opt/airflow$ airflow config get-value webserver warn_deployment_exposure
True
```
 So I don't think it is being set correctly. Maybe copy this file to the `/opt/airflow/`?

2023-04-07 22:39 UTC, jermnelson approved these changes

2023-04-07 22:40 UTC, merged