Inject Airflow environment variables in docker-compose config
sul-dlss/libsys-airflow pull request #288
Opened 2023-04-07 23:16 UTC by mjgiarlo

Connects to #287

This commit allows the running airflow services to be configured dynamically via environment variables.

2023-04-10 19:25 UTC, lwrubel commented on Dockerfile
> +COPY requirements.txt pyproject.toml poetry.lock ./
When using COPY with more than one source file, Docker expects the destination to be a directory and end with a `/`

2023-04-10 19:29 UTC, lwrubel commented
Puppet PR to accompany this: https://github.com/sul-dlss/puppet/pull/9411/files (will take it out of draft once this PR is reviewed to confirm it's the right set of variables).

All of the variables are in vault for dev. Prod and stage will need the new ones.

2023-04-10 23:52 UTC, jermnelson requested changes
Looks good overall. Just a request to update the README at https://github.com/sul-dlss/libsys-airflow#running-locally-with-docker to add these variables to the local `.env` file

2023-04-11 12:16 UTC, lwrubel commented
Thanks, that's a good suggestion. Instructions added.

2023-04-11 16:24 UTC, jermnelson approved these changes

2023-04-11 16:24 UTC, merged