Add apache-airflow-client to Python test dependencies
sul-dlss/libsys-airflow pull request #320
Opened 2023-04-18 16:01 UTC by mjgiarlo

Fixes #318

No idea if this is compatible with the 2.5.3 API, though.

2023-04-18 16:03 UTC, aaron-collier requested changes

2023-04-18 16:03 UTC, aaron-collier commented on pyproject.toml
> +apache-airflow-client = "2.5.1" # this should ideally be kept in sync with the airflow version but client releases are lagging
I think this needs to be in the main dependencies as we'll use it for interacting with airflow in the flask UI.

2023-04-18 16:17 UTC, edsu commented on pyproject.toml
> +apache-airflow-client = "2.5.1" # this should ideally be kept in sync with the airflow version but client releases are lagging
Kinda wondering if we should talk about how to install and run Airflow using Poetry in the Docker container?

2023-04-18 16:19 UTC, mjgiarlo commented on pyproject.toml
> +apache-airflow-client = "2.5.1" # this should ideally be kept in sync with the airflow version but client releases are lagging
I'm not saying it's not possible, but IIRC the Airflow documentation explicitly supports installation by `pip` and not by `poetry`. 🤷🏻‍♂️

2023-04-18 19:05 UTC, mjgiarlo commented
@aaron-collier @edsu Is this PR good to go now or should we make changes?

2023-05-02 17:14 UTC, aaron-collier commented
@mjgiarlo apologies, I've been meaning to get back to this. Yes, i think we still need it as task code will be required to instantiate dag runs, likely through the client, but if we find we can do everything in models, we can always back this out if we find it unused.

2023-05-02 17:14 UTC, aaron-collier approved these changes

2023-05-02 17:15 UTC, merged