Initial vendor management plugin config
sul-dlss/libsys-airflow pull request #342
Opened 2023-04-27 18:59 UTC by lwrubel

2023-04-27 20:20 UTC, lwrubel commented on docker-compose.yaml
> +    AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE: 'true'
This is just in docker-compose.yml to support development.

2023-04-27 20:21 UTC, lwrubel commented on libsys_airflow/plugins/vendor_management/templates/index.html
> +        <th>Acquisitions Unit</th>
Is this the right set of columns? Or should some of these be in the cell with the Organization ID?

2023-04-27 20:22 UTC, lwrubel commented on libsys_airflow/plugins/vendor_management/main.py
> +vendor_index_view_package = {
Flask app plugins seem to require a dropdown (category) and item.

2023-04-27 20:30 UTC, aaron-collier commented on libsys_airflow/plugins/vendor_management/main.py
> +from plugins.vendor_management.vendors import VendorManagementView
Can this live in plugins.vendor.... instead of vendor_management? Shouldn't be too bad to rename, right? We've started `vendor` with the marc_filter util and would like to stick with that.

2023-04-27 20:31 UTC, aaron-collier requested changes
Only a small suggestion to move into plugins/vendor instead of vendor_management

2023-04-27 20:59 UTC, lwrubel commented on libsys_airflow/plugins/vendor_management/main.py
> +from plugins.vendor_management.vendors import VendorManagementView
No problem. Re-named to `vendor`.

2023-04-27 23:15 UTC, ndushay approved these changes
approving because I know Aaron reviewed and is ready to approve.

2023-04-28 20:19 UTC, aaron-collier approved these changes

2023-04-28 20:20 UTC, merged