WIP Query vendor_loads db for vendors list
sul-dlss/libsys-airflow pull request #367
Opened 2023-05-04 21:54 UTC by lwrubel

Still needs tests

2023-05-05 20:06 UTC, lwrubel commented on libsys_airflow/plugins/vendor_app/vendors.py
> +from plugins.vendor.models import Vendor
I re-ordered and re-grouped the imports to follow PEP-8 https://peps.python.org/pep-0008/

2023-05-05 20:13 UTC, ndushay requested changes

2023-05-05 20:13 UTC, ndushay commented on libsys_airflow/plugins/vendor_app/vendors.py
> +from plugins.vendor.models import Vendor
I'm thinking along these lines, but again, I'm not sure of python convention:

```
import logging
import os
import requests

from airflow.models import Variable
from airflow.providers.postgres.hooks.postgres import PostgresHook
from flask_appbuilder import expose, BaseView as AppBuilderBaseView
from folioclient import FolioClient
from plugins.vendor.models import Vendor
from sqlalchemy.orm import Session
```

does that make my concern clearer?

2023-05-05 20:19 UTC, lwrubel commented
I realized I wasn't totally following PEP-8 and further adjusted the ordering to follow that. How's this look now? 

```
import logging
import os

from airflow.models import Variable
from airflow.providers.postgres.hooks.postgres import PostgresHook
from flask_appbuilder import expose, BaseView as AppBuilderBaseView
from folioclient import FolioClient
import requests
from sqlalchemy.orm import Session

from plugins.vendor.models import Vendor
```

2023-05-06 20:22 UTC, lwrubel commented
I've rebased to remove the merge conflict. I won't be available to take any changes further in this PR in the coming week while I'm away, so if there are further edits needed, would someone else be able to take them? Thanks!

2023-05-08 16:23 UTC, edsu approved these changes

2023-05-09 20:11 UTC, ndushay commented
@edsu if you want to resolve conflicts and fix the imports and then merge this, go for it.

2023-05-10 20:42 UTC, ndushay approved these changes

2023-05-10 20:43 UTC, merged