Set VendorFile.expected_execution in UI
sul-dlss/libsys-airflow pull request #499
Opened 2023-05-25 12:00 UTC by edsu

Add a view at `/vendors/file/{vendor-file-id}` that will present information about a VendorFile and allow the Expected Load Time to be updated. The input uses [&lt;input type="datetime-local"&gt;](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) in browsers instead of jQuery plugin (which was an option that I avoided).

The list of pending files in the Interface and Dashboard views now includes the VendorFile ID which lets you navigate to the new view.

A new `folio_load_scheduler` DAG was introduced which uses the `VendorFile.ready_for_folio_load()` class method to to look for VendorFiles that are ready for loading (expected_load_time is in the past, and the status is `fetched`). It is scheduled to run every hour and starts up `default_data_processor` DAGs for any files that it finds. The dynamic execution of `default_data_processor` DAGs was removed from the `data_fetcher` DAG. The `bin/files` program lets you see what files are ready for loading on the command line.

https://github.com/sul-dlss/libsys-airflow/assets/33829/c8b30adf-bbbd-420c-94ee-6e2440d69d14

Resolves #480

2023-05-25 12:53 UTC, justinlittman requested changes

2023-05-25 12:53 UTC, justinlittman commented on libsys_airflow/plugins/vendor_app/vendors.py
> +                request.form['expected-execution']
This doesn't actually change the execution date. That requires changing the dag instance.

2023-05-25 12:54 UTC, edsu commented on libsys_airflow/plugins/vendor_app/vendors.py
> +                request.form['expected-execution']
I didn't realize the information was duplicated. Is there an example of how to do that from the vendor_app yet?

2023-05-25 14:20 UTC, edsu commented
After a conversation with @justinlittman I now understand that simply updating the vendor_loads database in #499 wasn't enough to change when the DAG will actually I run, and I need to make some changes on the Airflow side of things for this rescheduling to work:

1. Move the update of `VendorFile.dag_run_id` from `libsys_airflow.dags.vendor.default_data_processor` (which currently executes as part of the data loading) to `libsys_airflow.dags.vendor.data_fetcher` where the DAG instance is created and scheduled. This will give the Vendor Loads web app the `dag_run_id` before it is run, so it will be able to update it.
2. Rename `VendorFile.expected_execution` to `VendorFile.dag_execution_date` in the vendor database, and make it a `DateTime` (not just a `Date`). Populate it from `libsys_airflow.dags.vendor.data_fetcher` when the DAG instance is created. *Question: what property should I use from the Dag instance?*
3. Update the Flask app to update the Dag instance when the user wants to reschedule the load, in addition to updating its own database.  *Question: Should I use the REST API or Python API for that?*

2023-05-31 20:56 UTC, edsu commented
It turns out adjusting the execution time of a DagRun is not something that most people do, and works against the grain of how Airtable is typically used. After some discussion we are going to try a different approach:

- [ ] Remove the dynamic creation of `default_data_processor` DAGs at the end of `data_fetcher`
- [ ] Create a new `load_scheduler` that runs hourly and queries the `vendor_files` table looking for files that need loading and creates `default_data_processor` DAGs as needed.

2023-06-02 13:38 UTC, edsu commented on libsys_airflow/dags/vendor/data_fetcher.py
> -    dag_run_kwargs = generate_dag_run_kwargs.partial(
Generating the dag runs has been moved to the folio_load_scheduler DAG which runs on a schedule

2023-06-02 13:39 UTC, edsu commented on libsys_airflow/dags/vendor/default_data_processor.py
> -
Updating the VendorFile has been moved to the `folio_load_scheduler` DAG

2023-06-02 13:40 UTC, edsu commented on libsys_airflow/dags/vendor/folio_load_scheduler.py
> +    TriggerDagRunOperator.partial(task_id="process_file").expand_kwargs(dag_run_kwargs)
This is a new DAG that runs hourly to see what files need to be loaded and starts a DagRun for them.

2023-06-02 13:41 UTC, edsu commented on libsys_airflow/plugins/vendor/download.py
> +            expected_load_time=expected_load_time,
The expected_load_time can be set right away.

2023-06-02 13:41 UTC, edsu commented on libsys_airflow/plugins/vendor/emails.py
> +        )
Guard against VENDOR_LOADS_TO_EMAIL not being set in the environment (not in dev compose environment).

2023-06-02 13:42 UTC, edsu commented on libsys_airflow/plugins/vendor/models.py
> +    expected_load_time = Column(DateTime, nullable=True)
The expected_load_time is a datetime now, not just a date.

2023-06-02 13:42 UTC, edsu commented on libsys_airflow/plugins/vendor/models.py
> +        ).all()
A class method for looking up VendorLoad files that need processing. It limits to the last 1000 files but maybe this will need to be reduced depending on how much Airflow can handle?

2023-06-02 13:43 UTC, edsu commented on libsys_airflow/plugins/vendor_app/templates/vendors/file.html
> +{% endblock %}
A view for a VendorFile that lets you edit the expected_load_time if it hasn't been loaded already.

2023-06-02 13:43 UTC, edsu commented on libsys_airflow/plugins/vendor_app/templates/vendors/interface.html
> +    <td><a href="{{ url_for('VendorManagementView.file', file_id=file.id) }}">{{ file.id }}</a></td>
Link to the File view.

2023-06-02 13:44 UTC, edsu commented on libsys_airflow/plugins/vendor_app/vendor_management.py
> +
Server side piece to the VendorFile view. It also lets a POST update the expected_load_time.

2023-06-02 13:45 UTC, edsu commented on tests/apps/vendor_app/test_file_view.py
> +        assert vendor_file.expected_load_time.time() == tomorrow.time()
Test that the VendorFile view is working.

2023-06-02 13:46 UTC, edsu commented on tests/vendor/test_schedule.py
> +        assert vendor_files[0].created < vendor_files[1].created
Test that `VendorFile.ready_for_folio_load` works as expected.

2023-06-02 13:46 UTC, edsu commented on vendor_loads_migration/versions/a634337e2c85_expected_load_time.py
> +    op.add_column('vendor_files', sa.Column('expected_load_time', sa.DateTime(), nullable=True))
Rename the column to reflec that it's the expected load time, and make it a DateTime.

2023-06-02 16:10 UTC, jermnelson approved these changes
A couple of questions related to execution timestamps and file limits but not blocking.

2023-06-02 16:10 UTC, jermnelson commented on libsys_airflow/dags/vendor/folio_load_scheduler.py
> +                execution_date = datetime.now()
Does it matter the execution_date uses the system's local timestamp vs. using `utcnow`?

2023-06-02 16:10 UTC, jermnelson commented on libsys_airflow/plugins/vendor/download.py
> +        expected_load_time = datetime.now()
See question above about `now` vs. `utcnow`

2023-06-02 16:10 UTC, jermnelson commented on libsys_airflow/plugins/vendor/models.py
> +        ).all()
Would setting the `max_active_runs` parameter for the processing DAGs address this problem?  Any DAG Runs beyond that threshold would be queued up, This would require any processing dags beside the default to also have the `max_active_runs` set as well.

2023-06-02 16:29 UTC, justinlittman requested changes
Most of these are just suggestions for your consideration.

2023-06-02 16:29 UTC, justinlittman commented on bin/files
> +# A utility for listing files that are ready to be loaded into Folio.
Can you say more about who might want to use this to solve what problem?

2023-06-02 16:29 UTC, justinlittman commented on bin/files
> +    session = Session()
This should probably be a `with Session() as session:`

2023-06-02 16:29 UTC, justinlittman commented on libsys_airflow/plugins/vendor/emails.py
> +        )
You should be able to use `_email_enabled()` see L62.

2023-06-02 16:29 UTC, justinlittman commented on libsys_airflow/plugins/vendor/models.py
> +        ).all()
1K seems fine until proven otherwise.

2023-06-02 16:29 UTC, justinlittman commented on libsys_airflow/plugins/vendor_app/templates/vendors/dashboard.html
> +        <td><a href="{{ url_for('VendorManagementView.file', file_id=file.id) }}">{{ file.id }}</a></td>
Instead of displaying the DB id, just link the filename?

2023-06-02 16:29 UTC, justinlittman commented on libsys_airflow/plugins/vendor_app/templates/vendors/interface.html
> +    <td><a href="{{ url_for('VendorManagementView.file', file_id=file.id) }}">{{ file.id }}</a></td>
Same here re: db id.

2023-06-02 16:34 UTC, justinlittman commented on libsys_airflow/plugins/vendor/models.py
> +        ).all()
The main reason for this limit was to address Airflow's XCOM limitation of an array (must have <1024 entries).

2023-06-02 16:36 UTC, justinlittman commented on libsys_airflow/plugins/vendor/models.py
> +    def ready_for_folio_load(cls, session: Session) -> List["VendorFile"]:
Can this be called "ready_for_data_import" for consistency?

2023-06-02 16:39 UTC, justinlittman commented on libsys_airflow/plugins/vendor/models.py
> +                VendorFile.status.in_([FileStatus.fetched]),
This needs to account for SKIP IMPORT vendor interfaces. These are vendor interfaces in which the folio_data_import_profile_uuid is null.

One possibility is to set the expected_load_time to null for these earlier in dowload.py and then ignoring any in this query with null expected_load_time.

2023-06-02 16:48 UTC, edsu commented on libsys_airflow/plugins/vendor/emails.py
> +        )
Fixed!

2023-06-02 16:52 UTC, edsu commented on libsys_airflow/dags/vendor/folio_load_scheduler.py
> +                execution_date = datetime.now()
I think you're right. We should be using utcnow() here I think?

2023-06-02 17:03 UTC, justinlittman commented
Based on testing in stage, there is a mismatch between the TZ stored in the DB for expected_load_time and the ready for load query.

2023-06-02 17:14 UTC, edsu commented on bin/files
> +    session = Session()
Ok, FWIW I was copying the approach taken in `bin/seed_vendors`.

2023-06-02 17:16 UTC, edsu commented on libsys_airflow/plugins/vendor_app/templates/vendors/dashboard.html
> +        <td><a href="{{ url_for('VendorManagementView.file', file_id=file.id) }}">{{ file.id }}</a></td>
The filename is currently linked to the download.

2023-06-02 17:18 UTC, edsu commented on libsys_airflow/plugins/vendor_app/templates/vendors/interface.html
> +    <td><a href="{{ url_for('VendorManagementView.file', file_id=file.id) }}">{{ file.id }}</a></td>
The filename is currently linked to the download here too.

2023-06-02 17:19 UTC, edsu commented on libsys_airflow/plugins/vendor/models.py
> +    def ready_for_folio_load(cls, session: Session) -> List["VendorFile"]:
I deemed `data_import` to be a bit too vague and wanted to be more explicit.

2023-06-02 17:25 UTC, justinlittman commented on libsys_airflow/plugins/vendor/models.py
> +    def ready_for_folio_load(cls, session: Session) -> List["VendorFile"]:
Agree, but `data_import` is the name of the Folio module/API.

2023-06-02 18:00 UTC, justinlittman commented on libsys_airflow/plugins/vendor_app/templates/vendors/file.html
> +      {{ _macros.fileDownload(file, file.vendor_filename) }}
For consistency, can you use the download icon?

2023-06-02 20:05 UTC, edsu commented on libsys_airflow/plugins/vendor_app/templates/vendors/file.html
> +      {{ _macros.fileDownload(file, file.vendor_filename) }}
I was being consistent with the Dashboard, but have brought both in line with the Interface view now.

2023-06-02 20:07 UTC, edsu commented
I'm going to ticket the timezone problem separately from this PR since there are already too many changes bundled into this PR.

2023-06-02 20:17 UTC, edsu commented on vendor_loads_migration/versions/1d954292be5e_merge_expected_load_time_changes.py
> +    pass
This came in because of a dual-heads migration conflict.

2023-06-02 20:41 UTC, justinlittman approved these changes
Approve pending docker-compose fixes.

2023-06-02 20:41 UTC, justinlittman commented on docker-compose.yaml
> +    AIRFLOW_VAR_DOWNLOAD_DAYS_AGO: 10000
This should not change.

2023-06-02 20:41 UTC, justinlittman commented on docker-compose.yaml
> -    SQLALCHEMY_WARN_20: 1
Why was this removed?

2023-06-02 20:44 UTC, edsu commented on docker-compose.yaml
> +    AIRFLOW_VAR_DOWNLOAD_DAYS_AGO: 10000
Whoops, nice catch -- that was from me testing.

2023-06-02 20:44 UTC, edsu commented on docker-compose.yaml
> -    SQLALCHEMY_WARN_20: 1
It was an accident, I will restore.

2023-06-02 20:58 UTC, merged