Add Folio job execution UUID column to VendorFile model
sul-dlss/libsys-airflow pull request #514
Opened 2023-05-26 19:15 UTC by mjgiarlo

Connects to #508

This commit restores to the VendorFile model a column that was previously removed from the DataLoad model. When the data processor runs and gets the Folio job execution ID, that value is saved to all associated VendorFile instances. This is needed so we can construct links to Folio job executions, e.g., so users can get more information about vendor file loading errors (#508).

2023-05-26 19:24 UTC, justinlittman requested changes

2023-05-26 19:24 UTC, justinlittman commented on libsys_airflow/dags/vendor/default_data_processor.py
> +    VendorFile.update_batch_with_job_execution_id(
This should probably be in data import. I don't think it will work correctly in this location.

2023-05-26 19:24 UTC, justinlittman commented on libsys_airflow/plugins/vendor/models.py
> +    def update_batch_with_job_execution_id(
Since this is only going to be used in data import, I would put it there.

2023-05-26 20:07 UTC, mjgiarlo commented on libsys_airflow/dags/vendor/default_data_processor.py
> +    VendorFile.update_batch_with_job_execution_id(
OK, moved this functionality into `data_import.py`

2023-05-26 20:07 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/models.py
> +    def update_batch_with_job_execution_id(
K, I moved it there. Thanks!

2023-05-27 04:17 UTC, mjgiarlo commented on libsys_airflow/dags/vendor/default_data_processor.py
> +        params["vendor_interface_uuid"],
We need to know the vendor interface in the data import task now.

2023-05-27 04:18 UTC, mjgiarlo commented on libsys_airflow/plugins/folio/data_import.py
> +    session=None,
Allow injection of a session for testing purposes.

2023-05-27 04:19 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor_app/templates/vendors/_macros.html
> +  {% if file.folio_job_execution_uuid == None %}
NOTE: Yes, we're adding links not only to loading_error files in the dashboard but any files that have a job execution ID. More linkage = better?

2023-05-27 04:19 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor_app/vendors.py
> +            .query(VendorFile)
This was a bug/typo.

2023-05-30 10:29 UTC, edsu submitted a review, later dismissed

2023-05-30 10:29 UTC, edsu commented on libsys_airflow/plugins/folio/data_import.py
> +    session=None,
Can the session be mocked in the unit test?

2023-05-30 10:29 UTC, edsu commented on libsys_airflow/plugins/folio/data_import.py
> +    with session or _session() as db_session:
If session is mocked correctly this should not be needed.

2023-05-30 10:29 UTC, edsu commented on libsys_airflow/plugins/vendor_app/templates/vendors/_macros.html
> +  {% if file.folio_job_execution_uuid == None %}
I don't know if this changes things but I've been working on a "file" view as part of #480

2023-05-30 11:25 UTC, justinlittman requested changes

2023-05-30 11:25 UTC, justinlittman commented on libsys_airflow/plugins/folio/data_import.py
> +    session=None,
Agree with Ed -- we've gotten away with not having to inject sessions in other tests. It would be slightly preferable to follow this pattern.

2023-05-30 11:25 UTC, justinlittman commented on libsys_airflow/plugins/folio/data_import.py
> +        for filename in _unique_dechunked_filenames(batch_filenames):
I think that there will only be 1 job execution id that needs to be set for 1 VendorFile. Further, you get the VendorFile name by including it as an argument for the task (i.e., no need to dechunk the filenames).

2023-05-30 15:42 UTC, mjgiarlo commented on libsys_airflow/plugins/folio/data_import.py
> +    session=None,
@edsu @justinlittman Good call, you bet.

2023-05-30 15:42 UTC, mjgiarlo commented on libsys_airflow/plugins/folio/data_import.py
> +    with session or _session() as db_session:
🙌🏻

2023-05-30 15:54 UTC, mjgiarlo commented on libsys_airflow/plugins/folio/data_import.py
> +    session=None,
Done.

2023-05-30 15:54 UTC, mjgiarlo commented on libsys_airflow/plugins/folio/data_import.py
> +    with session or _session() as db_session:
Removed.

2023-05-30 16:29 UTC, mjgiarlo commented on libsys_airflow/plugins/folio/data_import.py
> +        for filename in _unique_dechunked_filenames(batch_filenames):
I think I understood that and made the change. Have another look?

2023-05-30 17:45 UTC, justinlittman approved these changes
Approve pending green.

2023-05-31 00:05 UTC, merged