Add file load report task
sul-dlss/libsys-airflow pull request #539
Opened 2023-05-31 21:40 UTC by mjgiarlo

Connects to #267

This commit adds a new task, an Airflow sensor task, that generates and emails a report for a given vendor file that has already been loaded.

2023-05-31 21:42 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/emails.py
> +    return conf.has_option("smtp", "smtp_host")
Pulled up from below.

2023-05-31 21:42 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/emails.py
> +def _files_fetched_html_content(
Renamed `_html_content` since that function now only pertains to the "files fetched" portions of `emails.py`.

2023-05-31 21:43 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/emails.py
> +    # records_count: int,
Gotta figure out how to get this value from the MARC batch task earlier.

2023-05-31 21:44 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/emails.py
> +from datetime import date, datetime
`emails.py` is extended to handle not only the "files fetched email" use case but also the "file loaded email" use case.

2023-05-31 21:45 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/file_load_report.py
> +            return PokeReturnValue(is_done=False)
I ... think this is how to return this to its set schedule?

2023-05-31 21:46 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/file_load_report.py
> +@task.sensor(poke_interval=3600, timeout=60 * 60 * 24 * 5, mode="reschedule")
Run the task every hour for up to five days.

2023-05-31 21:46 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/file_load_report.py
> +        load_time = dag_run.start_date
No idea how close this is to the right incantation.

2023-05-31 21:47 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/marc.py
> +        # )
No idea how to stuff this value in xcom for usage above.

2023-05-31 21:57 UTC, aaron-collier commented on libsys_airflow/plugins/vendor/file_load_report.py
> +@task.sensor(poke_interval=3600, timeout=60 * 60 * 24 * 5, mode="reschedule")
This is one area of airflow I've had issue with, so may require some manually testing. If you run every hour with a 5 day timeout - we may likely end up with a large number of these running that ran for an hour and didn't find anything...

I'm not sure how best to address this, through concurrency settings or seeing if another one is already running and ending or something along those lines. Happy to chat quickly if that helps.

2023-05-31 22:01 UTC, aaron-collier commented on libsys_airflow/plugins/vendor/file_load_report.py
> +@task.sensor(poke_interval=3600, timeout=60 * 60 * 24 * 5, mode="reschedule")
https://marclamberti.com/blog/airflow-sensors/

2023-05-31 22:05 UTC, aaron-collier commented on libsys_airflow/plugins/vendor/file_load_report.py
> +@task.sensor(poke_interval=3600, timeout=60 * 60 * 24 * 5, mode="reschedule")
Wait, I think this is irrelevant in this case as it's not a recurring dag.

2023-05-31 22:28 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/file_load_report.py
> +        load_time = dag_run.start_date
@sul-dlss/infrastructure-team Maybe there's a more magical way to ask the containing DAG run for its start time?

2023-05-31 22:29 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/marc.py
> +        # )
Would be good to hear from @sul-dlss/infrastructure-team on this one.

2023-05-31 22:57 UTC, mjgiarlo commented
Does this error make sense to anyone?

![Screenshot from 2023-05-31 15-56-46](https://github.com/sul-dlss/libsys-airflow/assets/131982/6713ab09-33e6-46b3-b144-7d90d8630926)

2023-06-01 11:50 UTC, justinlittman commented on libsys_airflow/plugins/vendor/marc.py
> +        # )
Just return it from the task.

2023-06-01 11:53 UTC, justinlittman commented
The dates in the filename don't match? Do you need to mock `date` or `datetime`?

2023-06-01 15:26 UTC, mjgiarlo commented
> The dates in the filename don't match? Do you need to mock `date` or `datetime`?

It's more that the changes in this branch don't seem to touch anything near the marc helper. Maybe things are more tangled than they appear.

2023-06-01 15:52 UTC, mjgiarlo commented
> > The dates in the filename don't match? Do you need to mock `date` or `datetime`?
> 
> It's more that the changes in this branch don't seem to touch anything near the marc helper. Maybe things are more tangled than they appear.

🤷🏻‍♂️ It seems to have flapped back to working.

2023-06-01 20:48 UTC, justinlittman requested changes

2023-06-01 20:48 UTC, justinlittman commented on libsys_airflow/plugins/vendor/emails.py
> +        f"{vendor_name} ({vendor_code}) - ({filename}) - File Load Report",
Should this have the date? See L58

2023-06-01 20:48 UTC, justinlittman commented on libsys_airflow/plugins/vendor/emails.py
> +    folio_base_url = Variable.get("OKAPI_URL")
Is the okapi (API) URL different than the Folio UI URL?

2023-06-01 20:48 UTC, justinlittman commented on libsys_airflow/plugins/vendor/file_load_report.py
> +        file_loaded_email_task(
I'm confused why the task is being invoked from the sensor instead of being downstream from the sensor.

2023-06-01 20:48 UTC, justinlittman commented on libsys_airflow/plugins/vendor/file_load_report.py
> +        job_summary = folio_client.get(
How do we know if Folio is done?

2023-06-01 20:48 UTC, justinlittman commented on libsys_airflow/plugins/vendor/file_load_report.py
> +@task.sensor(poke_interval=3600, timeout=60 * 60 * 24 * 5, mode="reschedule")
Where is the sensor being added to a DAG?

2023-06-01 21:42 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/emails.py
> +        f"{vendor_name} ({vendor_code}) - ({filename}) - File Load Report",
#267 does not specify the date 🤷🏻‍♂️

2023-06-01 21:42 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/emails.py
> +    folio_base_url = Variable.get("OKAPI_URL")
Yep, sure is 🍻

2023-06-01 23:17 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/file_load_report.py
> +        file_loaded_email_task(
Because there is no containing DAG for the task that could hold a downstream task. I'll have a go at creating the DAG (as described in #510).

2023-06-01 23:18 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/file_load_report.py
> +        job_summary = folio_client.get(
We don't, good catch!

2023-06-07 10:26 UTC, justinlittman approved these changes
Approve pending renaming of XCOM.

2023-06-07 10:26 UTC, justinlittman commented on libsys_airflow/plugins/vendor/emails.py
> +        "mjgiarlo@stanford.edu",  # os.getenv('VENDOR_LOADS_TO_EMAIL'),
Just flagging this testing value.

2023-06-07 10:26 UTC, justinlittman commented on libsys_airflow/plugins/vendor/marc.py
> +        return {"records_count": 0, "marc_path": filename}
For consistency, can you have the return value be `marc_filename`, as it is only a filename and does not include the path?

2023-06-07 13:44 UTC, edsu commented on libsys_airflow/plugins/vendor/file_load_report.py
> +        xcom_value=json.dumps(
Another option here would be to have the Sensor simply return that it is done, and then have the reporting task fetch the details again instead of trying to pass them along in Xcom.

2023-06-07 15:17 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/file_load_report.py
> +        xcom_value=json.dumps(
👍🏻

2023-06-07 15:46 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/marc.py
> +    return {"records_count": len(records), "marc_path": new_marc_path}
@justinlittman is `new_marc_path` also just a filename? I'm trying to figure out whether the return dict should always have a count and a filename or whether it also needs to sometimes return a path.

2023-06-07 15:51 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/file_load_report.py
> +        xcom_value=json.dumps(
Left the comment.

2023-06-07 17:05 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/marc.py
> +        return {"records_count": 0, "marc_path": filename}
Done.

2023-06-07 17:29 UTC, mjgiarlo commented on libsys_airflow/plugins/vendor/emails.py
> +        "mjgiarlo@stanford.edu",  # os.getenv('VENDOR_LOADS_TO_EMAIL'),
Done.

2023-06-07 18:38 UTC, merged