data_import: _record_status sets vendor_file.loaded_timestamp when updating .status to FileStatus.loaded
sul-dlss/libsys-airflow pull request #588
Opened 2023-06-06 18:34 UTC by jmartin-sul

closes #555

i haven't done a data load myself yet, so i was a bit unsure how to test this realistically.  but happy to do that either locally or in a deployed env if there or instructions or if someone wouldn't mind pairing on it?

2023-06-06 18:50 UTC, jmartin-sul commented on libsys_airflow/plugins/folio/data_import.py
> +            vendor_file.loaded_timestamp = datetime.utcnow()
on the one hand, it felt a bit weird adding this status-specific conditional logic to a general status update function.  on the other hand, it is private to the module, and doing something more generalizable, like having it take an optional callback function, seemed like overkill.  and the function is very much about `VendorFile.status`, which this timestamp is directly related to (and it's not like the function now knows about another class or variable).

happy to revisit if desired.

2023-06-06 18:50 UTC, jmartin-sul commented on tests/test_data_import.py
> +    after_record_loaded_time = datetime.utcnow()
this pattern for timestamp checking always feels a bit clunky to me (in any language), but i like the precision of it compared to just checking for a non-`None` timestamp.  happy to revisit if there's a more concise or idiomatic way to do this.

2023-06-08 12:53 UTC, justinlittman requested changes

2023-06-08 12:53 UTC, justinlittman commented on tests/test_data_import.py
> +    after_record_loaded_time = datetime.utcnow()
I'm not a huge fan of, as it seems to be a risk of being flaky. How about mocking out datetime? (Happy to pair on this.)

2023-06-09 11:43 UTC, justinlittman approved these changes

2023-06-09 11:43 UTC, merged