Support for Instance Stat Codes tsv File
sul-dlss/libsys-airflow pull request #705
Opened 2023-07-11 20:47 UTC by jermnelson

Fixes #563

2023-07-11 20:49 UTC, jermnelson commented on tests/test_instances.py
> +            "\ufeffCKEY\tITEM_TYPE\tITEM_CAT1",
Was seeing this utf-8 code in the `CKEY` column header in some of the instatcode.tsv files, fixed by explicitly the `fieldnames` in the reader so it doesn't matter if fixed in the future.

2023-07-11 23:51 UTC, shelleydoljack commented on tests/test_instances.py
> +            "\ufeffCKEY\tITEM_TYPE\tITEM_CAT1",
Ugh, BOM. Weird it is only in some of them and not all of them. The code that is generating these files is the same for each ckey range. I won't worry about it since you've got a fix for it. :)

2023-07-13 16:32 UTC, shelleydoljack requested changes

2023-07-13 16:32 UTC, shelleydoljack commented on libsys_airflow/plugins/folio/instances.py
> +                        "suppress": False,  # discoverySuppress as default
DATABASE is an item type so need to also evaluate ITEM_TYPE column. And ckey 10361029 has DATABASE  item type and MARCIVE item cat1.

2023-07-13 17:34 UTC, jermnelson commented on libsys_airflow/plugins/folio/instances.py
> +                        "suppress": False,  # discoverySuppress as default
Thanks @shelleydoljack, latest commit now adds `ITEM_TYPE` if found in the lookup_stat_codes along with a test using the example you provided.

2023-07-13 18:04 UTC, shelleydoljack approved these changes

2023-07-13 18:08 UTC, merged