Add code coverage with github actions
sul-dlss/libsys-airflow pull request #71
Opened 2022-03-28 17:23 UTC by jgreben

2022-03-29 21:04 UTC, jermnelson commented
I think we want to exclude the `tests` directory and the `folio_migration_tools` repository. I created a  `.coveragerc` file with with contents to  excludes these directories:
```
[run]
omit = 
    plugins/tests/*
    *migration_tools/*
```

2022-03-29 21:07 UTC, jermnelson requested changes
Looks good. Just a couple of observations about the code coverage picking up the `folio_migration_tools` code and I think we want to exclude the tests. Also do we need the sqlite database `.coverage` file checked in the source code?

2022-03-29 22:47 UTC, jgreben commented on .github/workflows/python-app.yml
>          git clone https://github.com/FOLIO-FSE/folio_migration_tools.git /Users/Shared/folio_migration_tools --depth=2
Ok so I added the .coveragerc file. That should remove `folio_migration_tools` from the coverage, right? I need to keep the `Install support repos` task in the workflow for the test to be able to run. Coveralls is not updating right now, so we can't see the most recent build.

2022-03-29 22:58 UTC, jgreben commented on .github/workflows/python-app.yml
>          git clone https://github.com/FOLIO-FSE/folio_migration_tools.git /Users/Shared/folio_migration_tools --depth=2
Also I removed the `.coverage` file.

2022-03-30 14:41 UTC, jermnelson approved these changes

2022-03-30 14:41 UTC, merged