OCLC API Wrapper for New and Updated MARC records
sul-dlss/libsys-airflow pull request #912
Opened 2024-03-22 16:23 UTC by jermnelson

Fixes #900 

TODO:
- [ ]  100% code coverage from new tests
- [ ] Test on airflow-dev

2024-03-26 18:33 UTC, shelleydoljack commented on libsys_airflow/plugins/data_exports/oclc_api.py
> +            result = httpx.post(
We should use a client instead of the helper functions, in order to take advantage of connection pooling, I think since we could be making a large number of requests in one dag run.

2024-03-27 22:24 UTC, jermnelson commented on libsys_airflow/plugins/data_exports/oclc_api.py
> +            result = httpx.post(
Done, see API code and tests

2024-04-17 17:04 UTC, shelleydoljack commented on libsys_airflow/plugins/data_exports/oclc_api.py
> +        for record in marc_records:
We should move the session outside the for-loop in order to not instantiate new sessions for each in the loop.

2024-05-15 21:42 UTC, jgreben approved these changes

2024-05-16 16:19 UTC, shelleydoljack requested changes
Are these real? https://github.com/sul-dlss/libsys-airflow/blob/4bdb39c732b5c8ad5f2bd337cc43648eadce9225/tests/data_exports/test_oclc_api.py#L248 I tried checking vault and did not see a key for oclc. I don't remember where these are stored.

2024-05-16 16:27 UTC, jermnelson commented
> Are these real?
> 
> https://github.com/sul-dlss/libsys-airflow/blob/4bdb39c732b5c8ad5f2bd337cc43648eadce9225/tests/data_exports/test_oclc_api.py#L248
> I tried checking vault and did not see a key for oclc. I don't remember where these are stored.

Nope, they are made up for the test.

2024-05-16 17:30 UTC, shelleydoljack approved these changes

2024-05-21 22:58 UTC, merged