872 gobi lists
sul-dlss/libsys-airflow pull request #937
Opened 2024-04-19 23:43 UTC by jgreben

2024-05-02 15:46 UTC, jermnelson requested changes
Suggestion for retrieving MARC fields to handle edge cases where multiple fields for the same tag exist or missing fields.

2024-05-02 15:46 UTC, jermnelson commented on libsys_airflow/plugins/data_exports/marc/gobi.py
> +                isbn = record["020"].get_subfields("a")[0]
Using the pymarc record field accessor like `record["020"]` (and the same for the fields "035", "856", and "956" below) only retrieves the first instance of the field. If there multiple instances of the field, this pattern will miss them; also if the field doesn't exist in the record, a `KeyError` exception will be raised and processing will stop. If you use the method  `record.get_fields("020")`, it will retrieve all instances of the field or an empty list if the field isn't present.

2024-05-13 21:31 UTC, jgreben commented
@jermnelson can you take another look at this PR. I made changes that hopefully address the problem of repeatable MARC fields.

2024-05-13 21:41 UTC, jermnelson requested changes
One suggested change so we check all of the isbns.

2024-05-13 21:41 UTC, jermnelson commented on libsys_airflow/plugins/data_exports/marc/gobi.py
> +                        break
Doing a `break` here will exit the for loop and any remaining isbns will not be checked. You probable want to use `continue` that will go to next member in the isbns list.

2024-05-13 22:48 UTC, jermnelson approved these changes

2024-05-13 22:48 UTC, merged