Process MARC as updates and deletes
sul-dlss/libsys-airflow pull request #963
Opened 2024-05-07 16:24 UTC by jgreben

2024-05-07 19:45 UTC, jermnelson requested changes
One small suggestion so we're not opening/reading files multiple times in for loops.

2024-05-07 19:45 UTC, jermnelson commented on libsys_airflow/plugins/data_exports/instance_ids.py
> +            with open(sqlfile) as sqf:
Is there a reason to open and read this file every iteration of both the inner `for` loop and the outer `for` loop on line 15? This is opening and reading the file 2x{number of files in sql_list}. I think you could move open file outside both of the for loops so we're only opening/reading it once.

2024-05-07 20:05 UTC, jgreben commented on libsys_airflow/plugins/data_exports/instance_ids.py
> +            with open(sqlfile) as sqf:
I think it needs to read and execute each sql file sequentially, and now it is doing it for everything in the `updates` sql folder and also for the `deletes` folder (even though there is only one sql file for deletes). If I am misinterpreting the need for this, maybe we can pair and you can help me figure it out.

2024-05-07 20:08 UTC, jgreben commented on libsys_airflow/plugins/data_exports/instance_ids.py
> +            with open(sqlfile) as sqf:
The file is a different file each time in the loop.

2024-05-07 20:13 UTC, jermnelson approved these changes

2024-05-08 15:32 UTC, jgreben commented
@shelleydoljack are we good to merge this?

2024-05-08 16:38 UTC, merged