Deduplicate uuids fetched from sql and handle absent uuids in 999
sul-dlss/libsys-airflow pull request #983
Opened 2024-05-14 20:31 UTC by jgreben

2024-05-14 21:34 UTC, jermnelson requested changes
Looks good! Small request to optimize regex outside of the for loop.

2024-05-14 21:34 UTC, jermnelson commented on libsys_airflow/plugins/data_exports/instance_ids.py
> +            results[kind] = list(np.unique(results[kind]))
Cool way to use np.unique!

2024-05-14 21:34 UTC, jermnelson commented on libsys_airflow/plugins/data_exports/marc/transformer.py
> +                    regex = re.compile(
I would move this compiled regex out of the for loop. You can instantiate prior to line 62. That way the regular expression will only be complied once and is usable for each iteration of the loop.

2024-05-14 21:34 UTC, jermnelson commented on libsys_airflow/plugins/data_exports/marc/transformer.py
> +                except Exception as e:
Good call, we want to generalize logging errors.

2024-05-15 20:55 UTC, shelleydoljack approved these changes

2024-05-15 21:33 UTC, jermnelson approved these changes

2024-05-15 21:33 UTC, merged