Refactors transmission tasks and test for GOBI selection and transmission DAGs
sul-dlss/libsys-airflow pull request #993
Opened 2024-05-16 20:41 UTC by shelleydoljack

Fixes #985

2024-05-16 21:22 UTC, jermnelson approved these changes

2024-05-16 21:22 UTC, jermnelson commented on tests/data_exports/test_transmission_tasks.py
> +@pytest.fixture(params=["pod", "gobi"])
Excited to see how to successfully use params in these fixtures.

2024-05-17 16:10 UTC, jgreben requested changes
We should discuss the implications to the gobi processing and then maybe merge this PR with or without changes and create other follow-on tickets.

2024-05-17 16:10 UTC, jgreben commented on tests/data_exports/test_transmission_tasks.py
> +            "2024030214.txt",
I don't think the gobi text files are setup to be placed in the marc file directory. See: https://github.com/sul-dlss/libsys-airflow/blob/2368d62e1090baa5576d8518b10166a1e0fa98e4/libsys_airflow/plugins/data_exports/marc/gobi.py#L24-L26

2024-05-17 16:10 UTC, jgreben commented on libsys_airflow/dags/data_exports/gobi_selections.py
> +            "marc_file_list": "{{ ti.xcom_pull('fetch_marc_records_from_folio') }}"
With this change we will need to also change the `gobi_list_from_marc_files` function to accept an "updates" and "deletes" dict. And this brings up another question, whether we can send updates as well as new records to gobi (whether they need them or not). We probably need a story time about this.

2024-05-17 19:01 UTC, shelleydoljack commented on libsys_airflow/dags/data_exports/gobi_selections.py
> +            "marc_file_list": "{{ ti.xcom_pull('fetch_marc_records_from_folio') }}"
I'll refactor `gobi_list_from_marc_files` so that it gets a `marc_list['updates']:` to process. Then we can fix it to get `marc_list['new']:` once that code has been written in https://github.com/sul-dlss/libsys-airflow/issues/996. Sound good?

2024-05-17 19:11 UTC, jgreben commented on libsys_airflow/dags/data_exports/gobi_selections.py
> +            "marc_file_list": "{{ ti.xcom_pull('fetch_marc_records_from_folio') }}"
Yes

2024-05-17 19:33 UTC, shelleydoljack commented on tests/data_exports/test_transmission_tasks.py
> +            "2024030214.txt",
Fixed in https://github.com/sul-dlss/libsys-airflow/pull/993/commits/590978fc47e33c701ab6af0b81b176973c23c75c

2024-05-17 19:34 UTC, shelleydoljack commented on libsys_airflow/dags/data_exports/gobi_selections.py
> +            "marc_file_list": "{{ ti.xcom_pull('fetch_marc_records_from_folio') }}"
"Fixed" in https://github.com/sul-dlss/libsys-airflow/pull/993/commits/b3934405eafc2516c48374a5a40f5a5145c5faa2

2024-05-17 20:01 UTC, jgreben approved these changes

2024-05-17 20:01 UTC, merged